// handler.ts — email-reply skill implementation.
//
// Replies to an existing email thread via the OutboundGateway. The gateway
// enforces contact blocked checks and content filtering before dispatch.
// This handler focuses on thread resolution (fetching the original message
// to extract the sender address and subject line).
//
// CC behaviour (three modes):
//   - cc absent (undefined): reply-all — auto-populate from original.to[] + original.cc[],
//     excluding the primary To recipient and every owned mailbox (ctx.selfEmails).
//   - cc === "": reply to sender only — no CC recipients.
//   - cc is a non-empty string: parse comma-separated addresses explicitly.
//
// sensitivity: "elevated" — enforced by the gateway's security pipeline.

import type { ToolHandler, ToolContext, ToolResult } from '../../../../src/skills/types.js';
import { registerOutboundContext } from '../../../../src/dispatch/context-bridge-parse.js';
import { boundTaskFromMetadata } from '../../../../src/agents/resumable-task.js';
import { buildReplyQuote } from '../../../../src/skills/_shared/reply-quote.js';
import { parseAttachmentInputs } from '../../../_shared/parse-attachments.js';
import { autoGeneratedSenderBlockReason } from '../../../../src/channels/email/auto-generated-mail.js';
import { deriveEmailReplyRecipientSet } from '../../../../src/channels/email/reply-recipients.js';

const MAX_BODY_LENGTH = 50000;

export class EmailReplyHandler implements ToolHandler {
  async execute(ctx: ToolContext): Promise<ToolResult> {
    const { reply_to_message_id: replyToMessageId, body, cc: ccInput, attachments: attachmentsRaw, context_bridge: contextBridgeRaw } = ctx.input as {
      reply_to_message_id?: string;
      body?: string;
      cc?: string;
      attachments?: unknown;
      context_bridge?: string;
    };

    const attachmentsParsed = parseAttachmentInputs(attachmentsRaw);
    if (typeof attachmentsParsed === 'string') {
      return { success: false, error: attachmentsParsed };
    }

    if (!replyToMessageId || typeof replyToMessageId !== 'string') {
      return { success: false, error: 'Missing required input: reply_to_message_id (string)' };
    }
    if (!body || typeof body !== 'string') {
      return { success: false, error: 'Missing required input: body (string)' };
    }

    if (body.length > MAX_BODY_LENGTH) {
      return { success: false, error: `body must be ${MAX_BODY_LENGTH} characters or fewer` };
    }

    if (!ctx.outboundGateway) {
      return {
        success: false,
        error: 'email-reply skill requires outboundGateway access. Declare "outboundGateway" in capabilities.',
      };
    }

    ctx.log.info({ replyToMessageId }, 'Replying to email via gateway');

    try {
      const original = await ctx.outboundGateway.getEmailMessage(replyToMessageId);

      const originalFrom = original.from[0]?.email;
      if (!originalFrom) {
        return {
          success: false,
          error: `Original message ${replyToMessageId} has no sender address — cannot reply`,
        };
      }

      // Defense in depth (#1734): relay suppress alone is not enough — Gate C can
      // still allow email-reply to the machine sender. Block that recipient only;
      // escalation to the principal (other recipients / channels) stays open.
      const autoGenBlock = autoGeneratedSenderBlockReason(ctx.taskMetadata, originalFrom);
      if (autoGenBlock) {
        return { success: false, error: autoGenBlock };
      }

      const baseSubject = original.subject.replace(/^Re:\s*/i, '');
      const replySubject = `Re: ${baseSubject}`;

      const ownedMailboxes = (ctx.selfEmails && ctx.selfEmails.length > 0)
        ? ctx.selfEmails
        : (ctx.selfEmail ? [ctx.selfEmail] : []);
      if (ccInput === undefined && ownedMailboxes.length === 0) {
        ctx.log.warn({ replyToMessageId }, 'email-reply: selfEmail not configured — Curia may CC itself in reply-all');
      }

      const recipientSet = deriveEmailReplyRecipientSet({
        originalFrom,
        originalTo: original.to,
        originalCc: original.cc,
        ccInput,
        selfEmails: ownedMailboxes,
      });
      if (!recipientSet) {
        return {
          success: false,
          error: 'Could not resolve reply recipients — original sender missing or cc is not a string',
        };
      }
      const ccAddresses = recipientSet.cc.length > 0 ? recipientSet.cc : undefined;

      // Append the quoted original message below the reply body. Formatting is
      // non-fatal — a quote failure must not block the reply from being sent.
      // htmlQuote is passed separately so it is appended after markdownToHtml(body)
      // in the gateway, preventing the HTML from being re-escaped.
      let htmlQuote: string | undefined;
      try {
        const candidate = buildReplyQuote(original, ctx.timezone, { format: 'html' });
        // Skip the quote silently if it would push the body past the size limit
        // (the agent-authored body already passed the guard above; a long thread
        // could tip the combined total over). The reply still goes out unquoted.
        htmlQuote = body.length + candidate.length <= MAX_BODY_LENGTH ? candidate : undefined;
      } catch (err) {
        ctx.log.warn(
          { err, replyToMessageId },
          'email-reply: buildReplyQuote failed (HTML stripping or date formatting) — sending without quote',
        );
      }

      const result = await ctx.outboundGateway.send({
        channel: 'email',
        to: originalFrom,
        subject: replySubject,
        body,
        replyToMessageId,
        htmlQuote,
        ...(ccAddresses ? { cc: ccAddresses } : {}),
        ...(attachmentsParsed.length > 0 ? { attachments: attachmentsParsed } : {}),
      }, {
        taskEventId: ctx.taskEventId,
        conversationId: ctx.conversationId,
        humanApproved: ctx.humanApproved,
        ...(attachmentsParsed.length > 0
          ? {
            reExecRecipe: {
              toolName: 'email-reply',
              partialPayload: ctx.input,
              description: `Send email reply with ${attachmentsParsed.length} attachment(s)`,
            },
            exportContext: {
              toolName: 'email-reply',
              agentId: ctx.agentId,
              exportItems: (ctx.input as Record<string, unknown>)['export_items'],
            },
          }
          : {}),
      });

      if (!result.success) {
        return { success: false, error: result.blockedReason ?? 'Email reply failed' };
      }

      // Register outbound context entry (best-effort, always fires).
      // Pass the agent-authored body only — not quotedBody — so outbound context stores
      // the meaningful reply content without the formatting-only quote block.
      await registerOutboundContext(ctx.outboundContext, contextBridgeRaw, {
        channelId: 'email',
        content: body,
        agentId: ctx.agentId ?? 'coordinator',
        log: ctx.log,
        boundTask: boundTaskFromMetadata(ctx.taskMetadata as Record<string, unknown> | undefined),
      });

      ctx.log.info(
        { messageId: result.messageId, to: originalFrom, subject: replySubject, cc: ccAddresses },
        'Email reply sent successfully',
      );

      return {
        success: true,
        data: {
          message_id: result.messageId,
          to: originalFrom,
          subject: replySubject,
          // Return the CC list that was used; empty string when none.
          cc: ccAddresses?.join(', ') ?? '',
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      ctx.log.error({ err, replyToMessageId }, 'Failed to reply to email');
      return { success: false, error: `Failed to reply to email: ${message}` };
    }
  }
}
