// handler.ts — email-send skill implementation.
//
// Sends a new email via the OutboundGateway. The gateway enforces contact
// blocked checks and content filtering before dispatch — this handler
// focuses on input validation and formatting.
//
// Recipients are references by default (#2033, ADR-047): `to` and `cc` take a
// contact ID or "principal", and the gateway looks the address up from that
// contact's verified identities. A `#label` hint (`principal#personal`, or on
// each cc entry) asks for that labelled identity (#2047). `to_address` and
// `cc_addresses` are the deliberate raw path, for people with no contact record.
//
// sensitivity: "elevated" — enforced by the gateway's security pipeline.

import type { ToolHandler, ToolContext, ToolResult } from '../../../../src/skills/types.js';
import { registerOutboundContext } from '../../../../src/dispatch/context-bridge-parse.js';
import { boundTaskFromMetadata } from '../../../../src/agents/resumable-task.js';
import { buildReplyQuote } from '../../../../src/skills/_shared/reply-quote.js';
import { parseAttachmentInputs } from '../../../_shared/parse-attachments.js';
import { autoGeneratedSenderBlockReason } from '../../../../src/channels/email/auto-generated-mail.js';
import { emailAccountIdFromInput, replyToMessageIdFromInput } from '../../../../src/channels/email/account-id.js';
import { UnknownEmailAccountError, type OutboundGateway } from '../../../../src/skills/outbound-gateway.js';

const MAX_TO_LENGTH = 1000;
const MAX_SUBJECT_LENGTH = 500;
const MAX_BODY_LENGTH = 50000;

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function splitList(raw: string): string[] {
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

function parseRecipients(raw: string): string[] {
  return splitList(raw).map((email) => {
    if (!EMAIL_REGEX.test(email)) {
      throw new Error(`Invalid email address: ${email}`);
    }
    return email;
  });
}

/** Optional string input: undefined when absent or blank, an error when not a string. */
function optionalString(input: Record<string, unknown>, field: string): string | undefined | { error: string } {
  const value = input[field];
  if (value === undefined || value === null) return undefined;
  if (typeof value !== 'string') return { error: `${field} must be a string` };
  if (value.length > MAX_TO_LENGTH) return { error: `${field} must be ${MAX_TO_LENGTH} characters or fewer` };
  return value.trim().length > 0 ? value : undefined;
}

/**
 * Resolve each comma-separated reference to an address through the gateway.
 * An address in a reference field is refused with a pointer to the raw field,
 * so a send never mixes a typed address into the reference path.
 */
async function resolveReferenceList(
  gateway: OutboundGateway,
  raw: string,
  field: string,
  rawField: string,
  log: ToolContext['log'],
): Promise<{ addresses: string[]; contactIds: Array<string | undefined>; identityNames: string[] } | { error: string }> {
  const addresses: string[] = [];
  // Undefined for the alias: the principal's contact ID stays out of the model's
  // context (spec 09). Only a UUID the agent passed is echoed back.
  const contactIds: Array<string | undefined> = [];
  // Parallel to addresses: the label, or "primary" / "unlabelled". Never an address.
  const identityNames: string[] = [];
  for (const entry of new Set(splitList(raw))) {
    const resolved = await gateway.resolveRecipientReference('email', entry, { field, rawField });
    if (!resolved.ok) return { error: resolved.error };
    if (!EMAIL_REGEX.test(resolved.identifier)) {
      // A stored identity Nylas cannot address: a data defect. Refuse rather than guess,
      // and log the contact for an operator (never echo the ID: it may be the principal's).
      log.warn({ contactId: resolved.contactId, field }, 'email-send: verified email identity is not a valid address — refusing (#2033)');
      return {
        error: `The ${field} contact's verified email identity is not a valid address, so nothing was sent. It needs correcting in Contacts.`,
      };
    }
    if (addresses.includes(resolved.identifier)) continue;
    addresses.push(resolved.identifier);
    contactIds.push(resolved.kind === 'contact' ? resolved.contactId : undefined);
    // Always set, so identityNames stays aligned with addresses. A resolved
    // reference always names the identity (a label, "primary", or "unlabelled").
    identityNames.push(resolved.identityName);
  }
  return { addresses, contactIds, identityNames };
}

export class EmailSendHandler implements ToolHandler {
  async execute(ctx: ToolContext): Promise<ToolResult> {
    const input = ctx.input as {
      subject?: string;
      body?: string;
      reply_to_message_id?: string;
      attachments?: unknown;
      context_bridge?: string;
    };
    const { subject, body, attachments: attachmentsRaw, context_bridge: contextBridgeRaw } = input;
    // Same parsers as email-reply. account is honored only when threading, so a
    // new email cannot be sent from an arbitrary configured mailbox (#1832).
    const accountId = emailAccountIdFromInput(ctx.input);
    const replyToMessageId = replyToMessageIdFromInput(ctx.input);

    const fields: Record<'to' | 'to_address' | 'cc' | 'cc_addresses', string | undefined> = {
      to: undefined, to_address: undefined, cc: undefined, cc_addresses: undefined,
    };
    for (const field of Object.keys(fields) as Array<keyof typeof fields>) {
      const parsed = optionalString(ctx.input, field);
      if (typeof parsed === 'object') return { success: false, error: parsed.error };
      fields[field] = parsed;
    }
    const { to, to_address: toAddressRaw, cc, cc_addresses: ccAddressesRaw } = fields;

    if (!to && !toAddressRaw) {
      return {
        success: false,
        error: 'Missing recipient: pass to (a contact ID, or "principal" for the principal). Only for someone with no contact record, pass their address as to_address.',
      };
    }
    if (to && toAddressRaw) {
      return { success: false, error: 'Pass either to or to_address, not both.' };
    }
    if (!subject || typeof subject !== 'string') {
      return { success: false, error: 'Missing required input: subject (string)' };
    }
    if (!body || typeof body !== 'string') {
      return { success: false, error: 'Missing required input: body (string)' };
    }

    if (subject.length > MAX_SUBJECT_LENGTH) {
      return { success: false, error: `subject must be ${MAX_SUBJECT_LENGTH} characters or fewer` };
    }
    if (body.length > MAX_BODY_LENGTH) {
      return { success: false, error: `body must be ${MAX_BODY_LENGTH} characters or fewer` };
    }

    // Only a single To recipient is supported. Multiple addresses in the to field
    // would silently drop all but the first while reporting success for all of them.
    // Direct the caller to use cc for additional recipients instead.
    const SINGLE_TO = 'email-send supports a single To recipient. Use cc (or cc_addresses) for additional recipients.';
    if (to && splitList(to).length > 1) {
      return { success: false, error: SINGLE_TO };
    }
    if (to && splitList(to).length === 0) {
      return { success: false, error: 'to contains no contact reference' };
    }

    // Raw addresses are validated before the gateway check; references need the gateway.
    let rawToAddresses: string[] = [];
    let rawCcAddresses: string[] = [];
    try {
      if (toAddressRaw) rawToAddresses = parseRecipients(toAddressRaw);
      if (ccAddressesRaw) rawCcAddresses = parseRecipients(ccAddressesRaw);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return { success: false, error: message };
    }
    if (toAddressRaw && rawToAddresses.length === 0) {
      return { success: false, error: 'to_address contains no valid email addresses' };
    }
    if (rawToAddresses.length > 1) {
      return { success: false, error: SINGLE_TO };
    }

    if (accountId && !replyToMessageId) {
      return {
        success: false,
        error: 'account is only supported when reply_to_message_id is set. Omit account to send from the primary mailbox.',
      };
    }

    const attachmentsParsed = parseAttachmentInputs(attachmentsRaw);
    if (typeof attachmentsParsed === 'string') {
      return { success: false, error: attachmentsParsed };
    }

    if (!ctx.outboundGateway) {
      return {
        success: false,
        error: 'email-send skill requires outboundGateway access. Declare "outboundGateway" in capabilities.',
      };
    }

    // Resolve references to addresses (#2033). Every failure is closed: no send.
    let toAddresses = rawToAddresses;
    let toContactId: string | undefined;
    let toIdentity: string | undefined;
    if (to) {
      const resolved = await resolveReferenceList(ctx.outboundGateway, to, 'to', 'to_address', ctx.log);
      if ('error' in resolved) return { success: false, error: resolved.error };
      toAddresses = resolved.addresses;
      toContactId = resolved.contactIds[0];
      toIdentity = resolved.identityNames[0];
    }
    let ccAddresses: string[] = [...rawCcAddresses];
    let ccIdentities: string[] = [];
    if (cc) {
      const resolved = await resolveReferenceList(ctx.outboundGateway, cc, 'cc', 'cc_addresses', ctx.log);
      if ('error' in resolved) return { success: false, error: resolved.error };
      ccAddresses = [...resolved.addresses, ...ccAddresses];
      ccIdentities = resolved.identityNames;
    }

    // When replying, fetch the original message and append a quoted copy below
    // the reply body. Both the fetch and the formatting are non-fatal — if either
    // fails, proceed with the unquoted body and log a warning at the correct step.
    // htmlQuote is passed separately so it is appended after markdownToHtml(body)
    // in the gateway, preventing the HTML from being re-escaped.
    let htmlQuote: string | undefined;
    if (replyToMessageId) {
      let original: Awaited<ReturnType<typeof ctx.outboundGateway.getEmailMessage>> | undefined;
      try {
        original = await ctx.outboundGateway.getEmailMessage(replyToMessageId, accountId);
      } catch (err) {
        if (err instanceof UnknownEmailAccountError) {
          return { success: false, error: err.message };
        }
        ctx.log.warn(
          { err, replyToMessageId },
          'email-send: failed to fetch original message for quote — proceeding without quote',
        );
      }
      if (original !== undefined) {
        try {
          const candidate = buildReplyQuote(original, ctx.timezone, { format: 'html' });
          // Skip the quote silently if it would push the body past the size limit
          // (the agent-authored body already passed the guard above; the quote block
          // itself could tip a long thread over). The send still goes out unquoted.
          htmlQuote = body.length + candidate.length <= MAX_BODY_LENGTH ? candidate : undefined;
        } catch (err) {
          ctx.log.warn(
            { err, replyToMessageId },
            'email-send: failed to build reply quote — proceeding without quote',
          );
        }
      }
    }

    // Defense in depth (#1734): block email-send to the machine sender on an
    // auto-generated turn. Escalation to the principal (a different To) stays open.
    const autoGenBlock = autoGeneratedSenderBlockReason(ctx.taskMetadata, toAddresses[0]!);
    if (autoGenBlock) {
      return { success: false, error: autoGenBlock };
    }

    ctx.log.info({ to: toAddresses, subject, attachmentCount: attachmentsParsed.length }, 'Sending email via gateway');

    try {
      const result = await ctx.outboundGateway.send({
        channel: 'email',
        to: toAddresses[0]!,
        subject,
        body,
        cc: ccAddresses.length > 0 ? ccAddresses : undefined,
        replyToMessageId,
        htmlQuote,
        ...(accountId ? { accountId } : {}),
        ...(attachmentsParsed.length > 0 ? { attachments: attachmentsParsed } : {}),
      }, {
        taskEventId: ctx.taskEventId,
        conversationId: ctx.conversationId,
        humanApproved: ctx.humanApproved,
        ...(attachmentsParsed.length > 0
          ? {
            reExecRecipe: {
              toolName: 'email-send',
              partialPayload: ctx.input,
              description: `Send email with ${attachmentsParsed.length} attachment(s) to ${toAddresses[0]}`,
            },
            exportContext: {
              toolName: 'email-send',
              agentId: ctx.agentId,
              exportItems: (ctx.input as Record<string, unknown>)['export_items'],
            },
          }
          : {}),
      });

      if (!result.success) {
        return { success: false, error: result.blockedReason ?? 'Email send failed' };
      }

      // Register outbound context entry (best-effort, always fires).
      await registerOutboundContext(ctx.outboundContext, contextBridgeRaw, {
        channelId: 'email',
        content: body,
        agentId: ctx.agentId ?? 'coordinator',
        log: ctx.log,
        boundTask: boundTaskFromMetadata(ctx.taskMetadata as Record<string, unknown> | undefined),
      });

      return {
        success: true,
        data: {
          message_id: result.messageId,
          // The resolved address. Reply-lock and the activity log read this field.
          to: toAddresses.join(', '),
          ...(toContactId ? { contact_id: toContactId } : {}),
          ...(toIdentity ? { to_identity: toIdentity } : {}),
          ...(ccIdentities.length > 0 ? { cc_identities: ccIdentities } : {}),
          subject,
        },
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      ctx.log.error({ err, to: toAddresses, subject }, 'Failed to send email');
      return { success: false, error: `Failed to send email: ${message}` };
    }
  }
}
