-- Up Migration

-- 033_global_unique_short_ref.sql
--
-- Replaces the per-task UNIQUE(task_id, short_ref) constraint with a globally
-- unique UNIQUE(short_ref) constraint. The previous scheme used a per-task
-- counter (email-1, cal-1...) which caused collisions: two separate email
-- conversations each generated "email-1" in their own task context, making
-- approve-action ambiguous.
--
-- The new scheme uses random 8-char hex refs generated by generateShortRef()
-- (~4 billion possibilities). short_refs are now globally unique across all
-- tasks — "approve email" always refers to exactly one pending row.
--
-- Existing resolved/expired rows have their short_refs NULLed out so the
-- new UNIQUE constraint can be added cleanly. Active pending rows keep their
-- short_refs; any that happen to collide globally would be flagged by the
-- pre-check below.

-- Step 1: NULL out short_refs for all non-pending rows.
-- Any row with a terminal outcome (approved, denied, dismissed, expired) no longer
-- needs a short_ref for approval lookup. Clearing them removes the per-task
-- duplicates (e.g. two "email-1" rows in different tasks) that would otherwise
-- block the new global UNIQUE constraint. We intentionally do NOT filter by
-- expires_at here — a terminal-outcome row with a future expires_at (e.g. set
-- by a bug or manual intervention) would survive and potentially conflict.
UPDATE autonomy_action_log
SET short_ref = NULL
WHERE outcome != 'pending_approval';

-- Step 2: Pre-check for any remaining short_ref duplicates among active pending
-- rows. Should never occur in practice (each task just started), but guards
-- against a confusing ALTER TABLE failure if it somehow does.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM autonomy_action_log
    WHERE short_ref IS NOT NULL
    GROUP BY short_ref
    HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'Cannot add UNIQUE constraint: duplicate short_ref values exist among active '
      'pending_approval rows. Run: SELECT short_ref, COUNT(*) FROM autonomy_action_log '
      'WHERE short_ref IS NOT NULL GROUP BY short_ref HAVING COUNT(*) > 1; '
      'to find them, then manually expire or reassign before re-running this migration.';
  END IF;
END
$$;

-- Step 3: Swap constraints — drop per-task, add global.
ALTER TABLE autonomy_action_log DROP CONSTRAINT uq_aal_task_short_ref;
ALTER TABLE autonomy_action_log ADD CONSTRAINT uq_aal_short_ref UNIQUE (short_ref);

-- Down Migration

ALTER TABLE autonomy_action_log DROP CONSTRAINT uq_aal_short_ref;
ALTER TABLE autonomy_action_log ADD CONSTRAINT uq_aal_task_short_ref UNIQUE (task_id, short_ref);
