import { describe, it, expect } from 'vitest';
import {
  classifyAutoGeneratedMail,
  parseCalendarMethod,
  toAutoGeneratedMetadata,
  buildAutoGeneratedPreamble,
} from '../../../../src/channels/email/auto-generated-mail.js';

describe('parseCalendarMethod', () => {
  it('extracts METHOD=REPLY from a content-type parameter', () => {
    expect(parseCalendarMethod('text/calendar; method=REPLY; charset=UTF-8')).toBe('REPLY');
  });

  it('is case-insensitive and accepts quoted values', () => {
    expect(parseCalendarMethod('text/calendar; METHOD="Cancel"')).toBe('CANCEL');
  });

  it('returns undefined when method is absent', () => {
    expect(parseCalendarMethod('text/calendar')).toBeUndefined();
    expect(parseCalendarMethod('application/pdf')).toBeUndefined();
  });
});

describe('classifyAutoGeneratedMail (#1734)', () => {
  const personSenderBase = {
    subject: 'Hello',
    bodyText: 'Looking forward to lunch tomorrow.',
    snippet: 'Looking forward to lunch tomorrow.',
    attachments: [] as Array<{ contentType: string; filename: string; isCalendarInvite?: boolean }>,
  };

  it('classifies a calendar RSVP reply (empty body, method=REPLY) as auto-generated', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Declined: Q3 Planning',
      bodyText: '',
      snippet: '',
      attachments: [
        {
          filename: 'invite.ics',
          contentType: 'text/calendar; method=REPLY; charset=UTF-8',
          isCalendarInvite: true,
        },
      ],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('calendar_reply');
    expect(result.actionable).toBe(false);
    expect(result.carveOuts).toEqual([]);
  });

  it('classifies empty-body + isCalendarInvite without method as calendar_reply', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Accepted: Sync',
      bodyText: '',
      snippet: '',
      attachments: [
        { filename: 'invite.ics', contentType: 'text/calendar', isCalendarInvite: true },
      ],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('calendar_reply');
  });

  it('does not treat a formal REQUEST invite with a body as auto-generated', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Invitation: Design review',
      bodyText: 'Please join us for the design review.',
      snippet: 'Please join us',
      attachments: [
        {
          filename: 'invite.ics',
          contentType: 'text/calendar; method=REQUEST',
          isCalendarInvite: true,
        },
      ],
    });
    expect(result.isAutoGenerated).toBe(false);
  });

  it('classifies out-of-office by subject and Auto-Submitted header', () => {
    const bySubject = classifyAutoGeneratedMail({
      ...personSenderBase,
      subject: 'Out of Office: Back Monday',
      bodyText: 'I am out of the office until Monday.',
      snippet: 'I am out of the office until Monday.',
    });
    expect(bySubject.isAutoGenerated).toBe(true);
    expect(bySubject.signals).toContain('ooo_subject');
    expect(bySubject.actionable).toBe(false);

    const byHeader = classifyAutoGeneratedMail({
      ...personSenderBase,
      subject: 'Re: Project update',
      bodyText: 'I received your message and will respond when I return.',
      snippet: 'I received your message',
      headers: [{ name: 'Auto-Submitted', value: 'auto-replied' }],
    });
    expect(byHeader.isAutoGenerated).toBe(true);
    expect(byHeader.signals).toContain('auto_submitted');
  });

  it('marks bounce notices as auto-generated AND actionable', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Undeliverable: Quarterly report',
      bodyText: 'Delivery has failed for the following recipients.',
      snippet: 'Delivery has failed',
      headers: [{ name: 'Auto-Submitted', value: 'auto-generated' }],
      attachments: [],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('auto_submitted');
    expect(result.actionable).toBe(true);
    expect(result.carveOuts).toContain('bounce');
  });

  it('marks payment failure, security alert, and hard-deadline mail as actionable', () => {
    const payment = classifyAutoGeneratedMail({
      subject: 'Payment failed',
      bodyText: 'Your payment failed for invoice 44.',
      snippet: 'Your payment failed',
      headers: [{ name: 'Auto-Submitted', value: 'auto-generated' }],
      attachments: [],
    });
    expect(payment.actionable).toBe(true);
    expect(payment.carveOuts).toContain('payment_failure');

    const security = classifyAutoGeneratedMail({
      subject: 'Security alert',
      bodyText: 'Suspicious login detected on your account.',
      snippet: 'Suspicious login',
      headers: [{ name: 'Auto-Submitted', value: 'auto-generated' }],
      attachments: [],
    });
    expect(security.carveOuts).toContain('security_alert');

    const deadline = classifyAutoGeneratedMail({
      subject: 'Action required by Friday',
      bodyText: 'Your license expires tomorrow.',
      snippet: 'Your license expires tomorrow',
      headers: [{ name: 'Precedence', value: 'bulk' }],
      attachments: [],
    });
    expect(deadline.isAutoGenerated).toBe(true);
    expect(deadline.carveOuts).toContain('hard_deadline');
  });

  it('does not flag a normal human email from the same contact', () => {
    const result = classifyAutoGeneratedMail(personSenderBase);
    expect(result).toEqual({
      isAutoGenerated: false,
      signals: [],
      actionable: false,
      carveOuts: [],
    });
  });

  it('ignores Auto-Submitted: no', () => {
    const result = classifyAutoGeneratedMail({
      ...personSenderBase,
      headers: [{ name: 'Auto-Submitted', value: 'no' }],
    });
    expect(result.isAutoGenerated).toBe(false);
  });
});

describe('toAutoGeneratedMetadata / buildAutoGeneratedPreamble', () => {
  it('maps classification onto the inbound metadata bag', () => {
    const meta = toAutoGeneratedMetadata({
      isAutoGenerated: true,
      signals: ['calendar_reply'],
      actionable: false,
      carveOuts: [],
    });
    expect(meta).toEqual({
      isAutoGenerated: true,
      autoGeneratedSignals: ['calendar_reply'],
      autoGeneratedActionable: false,
      autoGeneratedCarveOuts: [],
    });
  });

  it('builds a silence+escalate preamble for actionable carve-outs', () => {
    const preamble = buildAutoGeneratedPreamble({
      signals: ['auto_submitted'],
      carveOuts: ['bounce'],
    });
    expect(preamble).toContain('AUTO-GENERATED MAIL');
    expect(preamble).toContain('auto_submitted');
    expect(preamble).toContain('bounce');
    expect(preamble).toContain('NO_REPLY');
  });
});
