import { describe, it, expect } from 'vitest';
import {
  classifyAutoGeneratedMail,
  parseCalendarMethod,
  toAutoGeneratedMetadata,
  buildAutoGeneratedPreamble,
} from '../../../../src/channels/email/auto-generated-mail.js';

describe('parseCalendarMethod', () => {
  it('extracts METHOD=REPLY from a content-type parameter', () => {
    expect(parseCalendarMethod('text/calendar; method=REPLY; charset=UTF-8')).toBe('REPLY');
  });

  it('is case-insensitive and accepts quoted values', () => {
    expect(parseCalendarMethod('text/calendar; METHOD="Cancel"')).toBe('CANCEL');
  });

  it('returns undefined when method is absent', () => {
    expect(parseCalendarMethod('text/calendar')).toBeUndefined();
    expect(parseCalendarMethod('application/pdf')).toBeUndefined();
  });
});

describe('classifyAutoGeneratedMail (#1734)', () => {
  const personSenderBase = {
    subject: 'Hello',
    bodyText: 'Looking forward to lunch tomorrow.',
    snippet: 'Looking forward to lunch tomorrow.',
    attachments: [] as Array<{ contentType: string; filename: string; isCalendarInvite?: boolean }>,
  };

  it('classifies a calendar RSVP reply (empty body, method=REPLY) as auto-generated', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Declined: Q3 Planning',
      bodyText: '',
      snippet: '',
      attachments: [
        {
          filename: 'invite.ics',
          contentType: 'text/calendar; method=REPLY; charset=UTF-8',
          isCalendarInvite: true,
        },
      ],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('calendar_reply');
  });

  it('does NOT treat empty-body calendar attach without method as auto-generated', () => {
    // Ambiguous: real REQUEST invites often ship empty body + .ics with no MIME method.
    // Suppressing here silently drops meetings; leave for a layer that can read METHOD.
    const result = classifyAutoGeneratedMail({
      subject: 'Invitation: Design review',
      bodyText: '',
      snippet: '',
      attachments: [
        { filename: 'invite.ics', contentType: 'text/calendar', isCalendarInvite: true },
      ],
    });
    expect(result.isAutoGenerated).toBe(false);
    expect(result.signals).toEqual([]);
  });

  it('does not treat a formal REQUEST invite with a body as auto-generated', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Invitation: Design review',
      bodyText: 'Please join us for the design review.',
      snippet: 'Please join us',
      attachments: [
        {
          filename: 'invite.ics',
          contentType: 'text/calendar; method=REQUEST',
          isCalendarInvite: true,
        },
      ],
    });
    expect(result.isAutoGenerated).toBe(false);
  });

  it('classifies out-of-office by subject and Auto-Submitted header', () => {
    const bySubject = classifyAutoGeneratedMail({
      ...personSenderBase,
      subject: 'Out of Office: Back Monday',
      bodyText: 'I am out of the office until Monday.',
      snippet: 'I am out of the office until Monday.',
    });
    expect(bySubject.isAutoGenerated).toBe(true);
    expect(bySubject.signals).toContain('ooo_subject');

    const byHeader = classifyAutoGeneratedMail({
      ...personSenderBase,
      subject: 'Re: Project update',
      bodyText: 'I received your message and will respond when I return.',
      snippet: 'I received your message',
      headers: [{ name: 'Auto-Submitted', value: 'auto-replied' }],
    });
    expect(byHeader.isAutoGenerated).toBe(true);
    expect(byHeader.signals).toContain('auto_submitted');
  });

  it('classifies bounce notices as auto-generated via Auto-Submitted (no body-keyword actionability)', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Undeliverable: Quarterly report',
      bodyText: 'Delivery has failed for the following recipients.',
      snippet: 'Delivery has failed',
      headers: [{ name: 'Auto-Submitted', value: 'auto-generated' }],
      attachments: [],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('auto_submitted');
  });

  it('does not escalate marketing bulk mail just because the body says expires', () => {
    // Precedence: bulk + "expires" must NOT invent an actionable carve-out at classify time.
    const result = classifyAutoGeneratedMail({
      subject: 'Your 20% off code expires Sunday',
      bodyText: 'Last chance to save on spring styles. Your trial expires in 3 days.',
      snippet: 'Last chance to save',
      headers: [{ name: 'Precedence', value: 'bulk' }],
      attachments: [],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('precedence_bulk');
    expect(result).not.toHaveProperty('actionable');
    expect(result).not.toHaveProperty('carveOuts');
  });

  it('does not invent a security carve-out from phishing vocabulary alone', () => {
    const result = classifyAutoGeneratedMail({
      subject: 'Security alert: unusual sign-in',
      bodyText: 'Verify your identity. Password reset requested for your account.',
      snippet: 'Verify your identity',
      headers: [{ name: 'Auto-Submitted', value: 'auto-generated' }],
      attachments: [],
    });
    expect(result.isAutoGenerated).toBe(true);
    expect(result.signals).toContain('auto_submitted');
    expect(result).not.toHaveProperty('carveOuts');
  });

  it('does not flag a normal human email from the same contact', () => {
    const result = classifyAutoGeneratedMail(personSenderBase);
    expect(result).toEqual({
      isAutoGenerated: false,
      signals: [],
    });
  });

  it('ignores Auto-Submitted: no', () => {
    const result = classifyAutoGeneratedMail({
      ...personSenderBase,
      headers: [{ name: 'Auto-Submitted', value: 'no' }],
    });
    expect(result.isAutoGenerated).toBe(false);
  });
});

describe('toAutoGeneratedMetadata / buildAutoGeneratedPreamble', () => {
  it('maps classification onto the inbound metadata bag', () => {
    const meta = toAutoGeneratedMetadata({
      isAutoGenerated: true,
      signals: ['calendar_reply'],
    });
    expect(meta).toEqual({
      isAutoGenerated: true,
      autoGeneratedSignals: ['calendar_reply'],
    });
  });

  it('builds a silence preamble that leaves escalation judgment to the agent', () => {
    const preamble = buildAutoGeneratedPreamble({
      signals: ['auto_submitted'],
    });
    expect(preamble).toContain('AUTO-GENERATED MAIL');
    expect(preamble).toContain('auto_submitted');
    expect(preamble).toContain('NO_REPLY');
    expect(preamble).toMatch(/marketing/i);
  });
});
