// turn-guidance-triggers.ts — which trigger guidance an inbound turn gets (#1959).
//
// The dispatcher already decides every one of these triggers while it builds the
// coordinator's agent.task: whether the sender is the principal (liveTurn), whether the
// [ACTIVE OUTBOUND CONTEXT] block went in and what its entries carry, whether this is an
// email and whether Curia was CC'd. This function turns those facts into the keys the
// runtime renders (src/agents/prompts/turn-guidance.ts), so the guidance costs nothing on
// a turn without its trigger.

import type { TurnGuidanceKey } from '../agents/prompts/turn-guidance.js';
import { isTaskWakeReplyBinding } from './task-wake-reply.js';

export interface InboundGuidanceFacts {
  /** A live principal turn (stampOriginator). */
  liveTurn: boolean;
  /**
   * Metadata of the entries rendered into this turn's [ACTIVE OUTBOUND CONTEXT] block.
   * Empty when no block was injected (no entries, a non-principal turn, or a read failure).
   */
  injectedEntryMetadata: ReadonlyArray<Record<string, unknown> | null>;
  channelId: string;
  /** Email only: Curia was CC'd rather than addressed directly. */
  curiaCc: boolean;
  /** Non-principal auto-generated mail. Its preamble already says NO_REPLY and when to escalate. */
  autoGeneratedSuppress: boolean;
}

export function inboundTurnGuidance(facts: InboundGuidanceFacts): TurnGuidanceKey[] {
  // Machine mail gets nothing more: reply-shaping and reply mechanics do not apply to a
  // message the coordinator must not answer.
  if (facts.autoGeneratedSuppress) return [];

  const keys: TurnGuidanceKey[] = [];
  const entries = facts.injectedEntryMetadata;
  if (!facts.liveTurn) {
    keys.push('non-principal-reply-shaped');
  } else if (entries.length === 0) {
    keys.push('principal-reply-shaped');
  } else {
    keys.push('outbound-context');
    if (entries.some((m) => isTaskWakeReplyBinding(m))) keys.push('outbound-context-task-wake');
    if (entries.some((m) => typeof m?.['resume_token'] === 'string' && m['resume_token'] !== '')) {
      keys.push('outbound-context-clarification');
    }
    // Meeting-debrief prompts carry the meeting title as `subject` (agents/meeting-debrief.yaml).
    if (entries.some((m) => typeof m?.['subject'] === 'string' && m['subject'].trim() !== '')) {
      keys.push('outbound-context-debrief');
    }
  }

  if (facts.channelId === 'email') {
    if (facts.curiaCc) {
      if (facts.liveTurn) keys.push('email-cc-principal');
      keys.push('email-cc-reply');
    } else {
      keys.push('email-direct-reply');
    }
    keys.push('email-etiquette');
  }
  return keys;
}
