/**
 * Message-derived auto-generated mail classification (#1734).
 *
 * Keys on headers, explicit calendar METHOD, and OOO subjects — not on the
 * sender contact's `kind`. A human's Exchange client can emit RSVP declines
 * that look like ordinary correspondence if we only trust `kind=person`.
 *
 * Pure module: no bus, DB, or logger. Called from convertNylasMessage and
 * consumed by the dispatcher (reply suppress + preamble) and agent prompts.
 *
 * Actionability is NOT decided here. Keyword carve-outs over body text are the
 * wrong instrument at dispatch (bulk mail + "expires" ≠ CEO escalate; phishing
 * vocabulary must not select a privileged path). Dispatch suppresses the reply
 * and lets the coordinator judge escalation; ceo-inbox keeps LLM carve-outs.
 */

import type { EmailAttachment } from './nylas-client.js';

/** Signals that indicate the message itself is machine-generated. */
export type AutoGeneratedSignal =
  | 'auto_submitted'
  | 'precedence_bulk'
  | 'precedence_auto_reply'
  | 'x_auto_response_suppress'
  | 'x_autoreply'
  | 'calendar_reply'
  | 'calendar_cancel'
  | 'ooo_subject';

export interface AutoGeneratedMailClassification {
  isAutoGenerated: boolean;
  signals: AutoGeneratedSignal[];
}

export interface AutoGeneratedMailInput {
  subject: string;
  /** Plain-text body (HTML already stripped). Empty/whitespace counts as empty. */
  bodyText: string;
  snippet: string;
  headers?: Array<{ name: string; value: string }>;
  attachments: Array<Pick<EmailAttachment, 'contentType' | 'filename' | 'isCalendarInvite'>>;
}

/**
 * Extract the iCalendar METHOD parameter from a MIME content type
 * (e.g. `text/calendar; method=REPLY; charset=utf-8` → `REPLY`).
 */
export function parseCalendarMethod(contentType: string | undefined): string | undefined {
  if (!contentType) return undefined;
  const match = /(?:^|;)\s*method\s*=\s*"?([A-Za-z]+)"?/i.exec(contentType);
  return match?.[1]?.toUpperCase();
}

function headerValue(
  headers: Array<{ name: string; value: string }> | undefined,
  name: string,
): string | undefined {
  if (!headers || headers.length === 0) return undefined;
  const lower = name.toLowerCase();
  const found = headers.find((h) => h.name.toLowerCase() === lower);
  return found?.value?.trim();
}

function collectHeaderSignals(
  headers: Array<{ name: string; value: string }> | undefined,
): AutoGeneratedSignal[] {
  const signals: AutoGeneratedSignal[] = [];

  const autoSubmitted = headerValue(headers, 'Auto-Submitted');
  if (autoSubmitted && autoSubmitted.toLowerCase() !== 'no') {
    signals.push('auto_submitted');
  }

  const precedence = headerValue(headers, 'Precedence')?.toLowerCase();
  if (precedence === 'bulk' || precedence === 'list' || precedence === 'junk') {
    signals.push('precedence_bulk');
  } else if (precedence === 'auto_reply') {
    signals.push('precedence_auto_reply');
  }

  if (headerValue(headers, 'X-Auto-Response-Suppress')) {
    signals.push('x_auto_response_suppress');
  }

  const xAutoreply = headerValue(headers, 'X-Autoreply')?.toLowerCase();
  if (xAutoreply === 'yes' || xAutoreply === 'true') {
    signals.push('x_autoreply');
  }

  return signals;
}

/**
 * Calendar signals require an explicit MIME `method=` parameter.
 *
 * Ambiguous `.ics` / `text/calendar` attachments with no method (Calendly,
 * Eventbrite, empty-body Outlook REQUEST invites) must NOT be treated as
 * auto-generated — guessing `calendar_reply` silently drops real invitations.
 * METHOD is required in the iCalendar object; when the MIME parameter is
 * absent, a layer that can fetch the attachment should decide, not this
 * pure classifier.
 */
function collectCalendarSignals(
  attachments: AutoGeneratedMailInput['attachments'],
): AutoGeneratedSignal[] {
  const signals: AutoGeneratedSignal[] = [];

  for (const att of attachments) {
    // isCalendarInvite is consumed so the flag has a live reader (#1734 AC),
    // but method= is what distinguishes REPLY/CANCEL from REQUEST/unknown.
    const looksCalendar =
      att.isCalendarInvite === true ||
      parseCalendarMethod(att.contentType) !== undefined ||
      (att.filename?.toLowerCase().endsWith('.ics') ?? false);

    if (!looksCalendar) continue;

    const method = parseCalendarMethod(att.contentType);
    if (method === 'REPLY') {
      signals.push('calendar_reply');
    } else if (method === 'CANCEL') {
      signals.push('calendar_cancel');
    }
    // method=REQUEST, method absent, or other → not a signal here
  }

  return signals;
}

const OOO_SUBJECT =
  /^(?:(?:re|fw|fwd):\s*)*(?:out of office|automatic reply|auto(?:matic)?(?:\s+|-)reply|away from (?:the )?office)\b/i;

function collectOooSubjectSignal(subject: string): AutoGeneratedSignal[] {
  return OOO_SUBJECT.test(subject.trim()) ? ['ooo_subject'] : [];
}

/**
 * Classify whether an inbound email is machine-generated from message signals.
 *
 * Independent of contact `kind`. Does not judge actionability — that stays
 * with the agent (or ceo-inbox LLM carve-outs), not dispatch regexes.
 */
export function classifyAutoGeneratedMail(input: AutoGeneratedMailInput): AutoGeneratedMailClassification {
  const signals: AutoGeneratedSignal[] = [
    ...collectHeaderSignals(input.headers),
    ...collectCalendarSignals(input.attachments),
    ...collectOooSubjectSignal(input.subject),
  ];

  const uniqueSignals = [...new Set(signals)];
  return {
    isAutoGenerated: uniqueSignals.length > 0,
    signals: uniqueSignals,
  };
}

/** Compact metadata bag stored on inbound / agent.task metadata. */
export function toAutoGeneratedMetadata(
  classification: AutoGeneratedMailClassification,
): {
  isAutoGenerated: boolean;
  autoGeneratedSignals: AutoGeneratedSignal[];
} {
  return {
    isAutoGenerated: classification.isAutoGenerated,
    autoGeneratedSignals: classification.signals,
  };
}

/**
 * Preamble injected for non-principal auto-generated mail. Instructs silence
 * toward the sender; escalation judgment stays with the agent.
 */
export function buildAutoGeneratedPreamble(classification: {
  signals: readonly string[];
}): string {
  const signals = classification.signals.join(', ') || 'unknown';
  return (
    `[AUTO-GENERATED MAIL — message-derived signals: ${signals}. ` +
    `Do not reply to the sender — return exactly NO_REPLY as your entire response ` +
    `for the external channel. Escalate to the principal only when the content is ` +
    `genuinely actionable (bounce/delivery failure, payment failure, security alert ` +
    `from a verified sender, or a hard deadline) — marketing "expires"/"last chance" ` +
    `copy is not actionable. Otherwise stay silent.]\n`
  );
}
