/**
 * Message-derived auto-generated mail classification (#1734).
 *
 * Keys on headers, calendar attachment method, and body emptiness — not on the
 * sender contact's `kind`. A human's Exchange client can emit RSVP declines
 * that look like ordinary correspondence if we only trust `kind=person`.
 *
 * Pure module: no bus, DB, or logger. Called from convertNylasMessage and
 * consumed by the dispatcher (default no-reply) and agent prompts.
 */

import type { EmailAttachment } from './nylas-client.js';

/** Signals that indicate the message itself is machine-generated. */
export type AutoGeneratedSignal =
  | 'auto_submitted'
  | 'precedence_bulk'
  | 'precedence_auto_reply'
  | 'x_auto_response_suppress'
  | 'x_autoreply'
  | 'calendar_reply'
  | 'calendar_cancel'
  | 'ooo_subject';

/**
 * Carve-outs that keep auto-generated mail on the escalate path (mirror
 * ceo-inbox §4e-pre). Detection still marks `isAutoGenerated`; dispatch still
 * suppresses a default reply to the sender, but the coordinator runs so it can
 * escalate to the principal.
 */
export type AutoGeneratedCarveOut =
  | 'bounce'
  | 'payment_failure'
  | 'security_alert'
  | 'hard_deadline';

export interface AutoGeneratedMailClassification {
  isAutoGenerated: boolean;
  signals: AutoGeneratedSignal[];
  /** True when a carve-out signal requires principal escalation. */
  actionable: boolean;
  carveOuts: AutoGeneratedCarveOut[];
}

export interface AutoGeneratedMailInput {
  subject: string;
  /** Plain-text body (HTML already stripped). Empty/whitespace counts as empty. */
  bodyText: string;
  snippet: string;
  headers?: Array<{ name: string; value: string }>;
  attachments: Array<Pick<EmailAttachment, 'contentType' | 'filename' | 'isCalendarInvite'>>;
}

/**
 * Extract the iCalendar METHOD parameter from a MIME content type
 * (e.g. `text/calendar; method=REPLY; charset=utf-8` → `REPLY`).
 */
export function parseCalendarMethod(contentType: string | undefined): string | undefined {
  if (!contentType) return undefined;
  const match = /(?:^|;)\s*method\s*=\s*"?([A-Za-z]+)"?/i.exec(contentType);
  return match?.[1]?.toUpperCase();
}

function headerValue(
  headers: Array<{ name: string; value: string }> | undefined,
  name: string,
): string | undefined {
  if (!headers || headers.length === 0) return undefined;
  const lower = name.toLowerCase();
  const found = headers.find((h) => h.name.toLowerCase() === lower);
  return found?.value?.trim();
}

function isBodyEmpty(bodyText: string, snippet: string): boolean {
  return bodyText.trim().length === 0 && snippet.trim().length === 0;
}

function collectHeaderSignals(
  headers: Array<{ name: string; value: string }> | undefined,
): AutoGeneratedSignal[] {
  const signals: AutoGeneratedSignal[] = [];

  const autoSubmitted = headerValue(headers, 'Auto-Submitted');
  if (autoSubmitted && autoSubmitted.toLowerCase() !== 'no') {
    signals.push('auto_submitted');
  }

  const precedence = headerValue(headers, 'Precedence')?.toLowerCase();
  if (precedence === 'bulk' || precedence === 'list' || precedence === 'junk') {
    signals.push('precedence_bulk');
  } else if (precedence === 'auto_reply') {
    signals.push('precedence_auto_reply');
  }

  if (headerValue(headers, 'X-Auto-Response-Suppress')) {
    signals.push('x_auto_response_suppress');
  }

  const xAutoreply = headerValue(headers, 'X-Autoreply')?.toLowerCase();
  if (xAutoreply === 'yes' || xAutoreply === 'true') {
    signals.push('x_autoreply');
  }

  return signals;
}

function collectCalendarSignals(
  attachments: AutoGeneratedMailInput['attachments'],
  bodyEmpty: boolean,
): AutoGeneratedSignal[] {
  const signals: AutoGeneratedSignal[] = [];

  for (const att of attachments) {
    const isInvite =
      att.isCalendarInvite === true ||
      parseCalendarMethod(att.contentType) !== undefined ||
      (att.filename?.toLowerCase().endsWith('.ics') ?? false);

    if (!isInvite) continue;

    const method = parseCalendarMethod(att.contentType);
    if (method === 'REPLY') {
      signals.push('calendar_reply');
    } else if (method === 'CANCEL') {
      signals.push('calendar_cancel');
    } else if (bodyEmpty && (method === undefined || method === 'REQUEST')) {
      // Exchange decline notices often ship empty body + invite.ics with
      // method=REPLY already caught above; when method is absent but the body
      // is empty, treat as machine RSVP/notice rather than a formal REQUEST.
      // Explicit method=REQUEST with a non-empty body is a real invite — not
      // auto-generated here (bodyEmpty is false).
      if (method === undefined) {
        signals.push('calendar_reply');
      }
    }
  }

  return signals;
}

const OOO_SUBJECT =
  /^(?:(?:re|fw|fwd):\s*)*(?:out of office|automatic reply|auto(?:matic)?(?:\s+|-)reply|away from (?:the )?office)\b/i;

function collectOooSubjectSignal(subject: string): AutoGeneratedSignal[] {
  return OOO_SUBJECT.test(subject.trim()) ? ['ooo_subject'] : [];
}

const BOUNCE_RE =
  /\b(?:undeliverable|delivery status notification|mail delivery(?:\s+subsystem)?\s+failed|returned mail|delivery failure|permanent failure|mailbox (?:full|unavailable)|user unknown|delivery has failed|could not be delivered)\b/i;

const PAYMENT_RE =
  /\b(?:payment (?:failed|failure|declined)|failed payment|invoice overdue|past due|billing (?:issue|problem|failed)|card (?:declined|expired)|payment was (?:not|un)successful)\b/i;

const SECURITY_RE =
  /\b(?:security alert|suspicious (?:login|sign[- ]?in|activity)|unauthorized access|password reset|account (?:locked|suspended|compromised|disabled)|fraud alert|verify your (?:identity|account)|unusual sign[- ]?in)\b/i;

const DEADLINE_RE =
  /\b(?:expires?(?:\s+(?:today|tomorrow|on\b|in\s+\d+))?|deadline|action required by|must (?:respond|act|reply) by|final notice|last chance)\b/i;

function collectCarveOuts(subject: string, bodyText: string, snippet: string): AutoGeneratedCarveOut[] {
  const haystack = `${subject}\n${bodyText}\n${snippet}`;
  const carveOuts: AutoGeneratedCarveOut[] = [];
  if (BOUNCE_RE.test(haystack)) carveOuts.push('bounce');
  if (PAYMENT_RE.test(haystack)) carveOuts.push('payment_failure');
  if (SECURITY_RE.test(haystack)) carveOuts.push('security_alert');
  if (DEADLINE_RE.test(haystack)) carveOuts.push('hard_deadline');
  return carveOuts;
}

/**
 * Classify whether an inbound email is machine-generated from message signals.
 *
 * Independent of contact `kind`. Carve-outs set `actionable` so dispatch can
 * still escalate while suppressing a default reply to the sender.
 */
export function classifyAutoGeneratedMail(input: AutoGeneratedMailInput): AutoGeneratedMailClassification {
  const bodyEmpty = isBodyEmpty(input.bodyText, input.snippet);
  const signals: AutoGeneratedSignal[] = [
    ...collectHeaderSignals(input.headers),
    ...collectCalendarSignals(input.attachments, bodyEmpty),
    ...collectOooSubjectSignal(input.subject),
  ];

  // Deduplicate while preserving order
  const uniqueSignals = [...new Set(signals)];
  const carveOuts = collectCarveOuts(input.subject, input.bodyText, input.snippet);
  const isAutoGenerated = uniqueSignals.length > 0;

  return {
    isAutoGenerated,
    signals: uniqueSignals,
    actionable: isAutoGenerated && carveOuts.length > 0,
    carveOuts,
  };
}

/** Compact metadata bag stored on inbound / agent.task metadata. */
export function toAutoGeneratedMetadata(
  classification: AutoGeneratedMailClassification,
): {
  isAutoGenerated: boolean;
  autoGeneratedSignals: AutoGeneratedSignal[];
  autoGeneratedActionable: boolean;
  autoGeneratedCarveOuts: AutoGeneratedCarveOut[];
} {
  return {
    isAutoGenerated: classification.isAutoGenerated,
    autoGeneratedSignals: classification.signals,
    autoGeneratedActionable: classification.actionable,
    autoGeneratedCarveOuts: classification.carveOuts,
  };
}

/**
 * Preamble injected when auto-generated mail is still dispatched (actionable
 * carve-out). Instructs silence toward the sender and escalation to the principal.
 */
export function buildAutoGeneratedPreamble(classification: {
  signals: readonly string[];
  carveOuts: readonly string[];
}): string {
  const signals = classification.signals.join(', ') || 'unknown';
  const carveOuts = classification.carveOuts.join(', ') || 'none';
  return (
    `[AUTO-GENERATED MAIL — message-derived signals: ${signals}; ` +
    `actionable carve-out: ${carveOuts}. ` +
    `Do not reply to the sender — return exactly NO_REPLY as your entire response ` +
    `for the external channel. Escalate the actionable signal to the principal ` +
    `via their preferred channel or the bullpen if warranted.]\n`
  );
}
