import { htmlToText } from './html-to-text.js';
import type { NylasMessage, EmailAttachment } from './nylas-client.js';
import {
  classifyAutoGeneratedMail,
  toAutoGeneratedMetadata,
  type AutoGeneratedSignal,
} from './auto-generated-mail.js';

// ---------------------------------------------------------------------------
// Output types — represent the normalized shape fed into the message bus
// createInboundMessage() event. EmailParticipant is also used by the contact
// system to upsert participant records from inbound emails.
// ---------------------------------------------------------------------------

export interface EmailParticipant {
  email: string;
  name?: string;
  role: 'from' | 'to' | 'cc';
}

export interface ConvertedEmail {
  conversationId: string;
  channelId: 'email';
  /** The sender's email address, used as the bus senderId */
  senderId: string;
  /** Plain-text body with subject prepended for LLM context */
  content: string;
  metadata: {
    subject: string;
    nylasMessageId: string;
    nylasThreadId: string;
    participants: EmailParticipant[];
    receivedAt: Date;
    /**
     * True if SPF, DKIM, and DMARC all passed on the receiving provider's
     * Authentication-Results header (the first one). A later header the sender
     * added does not count, and an explicit fail on any header is unverified.
     * False when a check failed or the headers were absent.
     * Defense-in-depth: email From headers are trivially spoofable; this surfaces
     * provider-level validation results so the Coordinator can apply extra skepticism
     * to messages that failed sender verification.
     */
    senderVerified: boolean;
    /**
     * Curia's role in this email's recipient fields.
     * - 'to': Curia was directly addressed as a primary recipient
     * - 'cc': Curia was copied; someone else is the primary recipient
     * - 'bcc': Curia was blind-copied — not currently detectable from MIME headers
     *          alone, so this value is never set by the converter today.
     *
     * @TODO: BCC detection requires a provider-level signal (e.g. Nylas injecting a
     *        dedicated header when the grant email appears only in the BCC envelope).
     *        Until that signal is available, emails where Curia appears in neither To
     *        nor CC (i.e. genuine BCC) are indistinguishable from direct sends and
     *        default to 'to'. Track in a GitHub issue.
     */
    curiaRole: 'to' | 'cc' | 'bcc';
    /**
     * Email addresses from the To field, excluding Curia's own address.
     * Populated only when selfEmail is provided to convertNylasMessage.
     * Empty array when selfEmail is unknown, or when Curia is the only To recipient.
     * If Curia appears in To alongside other recipients, those other To addresses
     * are retained.
     */
    primaryRecipientEmails: string[];
    /** Non-inline file attachments on this email. Empty array when none. */
    attachments: EmailAttachment[];
    /**
     * Message-derived auto-generated indicator (#1734). Independent of the
     * sender contact's `kind` — a person's calendar client can emit machine mail.
     */
    isAutoGenerated: boolean;
    /** Signals that fired (headers, explicit calendar method, OOO subject). */
    autoGeneratedSignals: AutoGeneratedSignal[];
  };
}

/** Format bytes as a human-readable string (e.g. 1536 → "1.5 KB"). */
function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / Math.pow(1024, i);
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[i]}`;
}

function authenticationResultsHeaders(
  headers: Array<{ name: string; value: string }>,
): Array<{ name: string; value: string }> {
  // Header names are case-insensitive (RFC 7601 §2.2).
  return headers.filter((h) => h.name.toLowerCase() === 'authentication-results');
}

/** SPF, DKIM, and DMARC each reported as pass on this one header. */
function authenticationMechanismsPass(value: string): boolean {
  // \b after "pass" guards against hypothetical tokens like "spf=passthrough".
  return /\bspf=pass\b/i.test(value) && /\bdkim=pass\b/i.test(value) && /\bdmarc=pass\b/i.test(value);
}

/** An explicit fail for SPF, DKIM, or DMARC. softfail and other results are not this. */
function authenticationMechanismFailed(value: string): boolean {
  return /\bspf=fail\b/i.test(value) || /\bdkim=fail\b/i.test(value) || /\bdmarc=fail\b/i.test(value);
}

/**
 * Parse Authentication-Results (RFC 7601) and return true only when the
 * receiving provider authenticated the message.
 *
 * The receiving MTA prepends its header, so the first Authentication-Results
 * header is the provider's. A later header is ordinary message text: a sender
 * can add `spf=pass dkim=pass dmarc=pass` under some other authserv-id, and
 * RFC 7601 §5 only says the receiver SHOULD remove headers that claim its own
 * id. Trusting any header would let that forgery win (#2071).
 *
 * An explicit spf, dkim, or dmarc fail on any header also returns false, so a
 * provider failure still blocks when the header list is reversed.
 *
 * Returns false when:
 * - headers are absent (the fetch did not ask for fields: 'include_headers')
 * - the Authentication-Results header is missing
 * - the provider header lacks a pass for SPF, DKIM, or DMARC
 * - any header reports spf=fail, dkim=fail, or dmarc=fail
 *
 * Fails closed: absent information is treated as unverified, not as verified.
 */
export function parseSenderVerified(headers?: Array<{ name: string; value: string }>): boolean {
  if (!headers || headers.length === 0) return false;

  const authHeaders = authenticationResultsHeaders(headers);
  const providerHeader = authHeaders[0];
  if (!providerHeader) return false;
  if (authHeaders.some((h) => authenticationMechanismFailed(h.value))) return false;
  return authenticationMechanismsPass(providerHeader.value);
}

/**
 * Determine Curia's role in the email (To vs CC) and collect the primary recipients.
 *
 * Case-insensitive comparison — email addresses are case-insensitive per RFC 5321.
 *
 * Returns 'to' as the fail-safe default when selfEmail is absent or not found in
 * either To or CC (e.g. genuine BCC, which is not currently detectable).
 */
function resolveCuriaRole(
  toList: Array<{ email: string }>,
  ccList: Array<{ email: string }>,
  selfEmail: string,
): { curiaRole: 'to' | 'cc' | 'bcc'; primaryRecipientEmails: string[] } {
  const self = selfEmail.toLowerCase();

  const inTo = toList.some((p) => p.email.toLowerCase() === self);
  if (inTo) {
    // Curia is a primary recipient — other To addresses (if any) are also primary.
    const primaryRecipientEmails = toList
      .map((p) => p.email)
      .filter((e) => e.toLowerCase() !== self);
    return { curiaRole: 'to', primaryRecipientEmails };
  }

  const inCc = ccList.some((p) => p.email.toLowerCase() === self);
  if (inCc) {
    // Curia was copied — the To addresses are the true primary recipients.
    const primaryRecipientEmails = toList.map((p) => p.email);
    return { curiaRole: 'cc', primaryRecipientEmails };
  }

  // selfEmail not found in To or CC — likely BCC, which MIME headers don't expose.
  // Default to 'to' (fail-safe: treat as a direct message rather than silently
  // misclassifying). BCC detection requires provider-level support; see @TODO above.
  return { curiaRole: 'to', primaryRecipientEmails: [] };
}

/**
 * Convert a Nylas message to a Curia inbound message shape.
 *
 * Decisions made here:
 * - conversationId uses the thread ID so all emails in a thread share the
 *   same working memory scope in the agent layer.
 * - Content is plain-text extracted from HTML (better for LLMs than raw HTML).
 * - Subject is prepended so agents always see it regardless of how the body
 *   was formatted.
 * - All participants (from/to/cc) are surfaced so the contact system can
 *   upsert or update relationship records in one pass.
 * - senderVerified is derived from the Authentication-Results header (if present).
 * - curiaRole and primaryRecipientEmails are derived from selfEmail when provided,
 *   allowing the dispatcher to surface whether Curia was directly addressed or CC'd.
 *
 * @param msg - The Nylas message to convert.
 * @param selfEmail - Curia's own email address for this account. When provided,
 *   the converter determines whether Curia appears in the To or CC field and
 *   populates curiaRole and primaryRecipientEmails accordingly. When omitted,
 *   curiaRole defaults to 'to' and primaryRecipientEmails is empty.
 */
export function convertNylasMessage(msg: NylasMessage, selfEmail?: string): ConvertedEmail {
  // Use ?? 'unknown' so an empty from array doesn't throw
  const fromEmail = msg.from[0]?.email ?? 'unknown';

  // Thread ID groups related emails into a single conversation in the bus
  const conversationId = `email:${msg.threadId}`;

  // htmlToText returns '' for an empty/falsy body, so also check snippet
  const bodyText = msg.body ? htmlToText(msg.body) : '';

  // Cap email body at 50KB of text to prevent context stuffing and excessive token usage.
  // Emails larger than this are truncated with a note.
  const MAX_BODY_LENGTH = 50_000;
  let content = bodyText || msg.snippet || '(empty email)';
  if (content.length > MAX_BODY_LENGTH) {
    content = content.slice(0, MAX_BODY_LENGTH) + '\n\n[Email truncated — original was ' + content.length + ' characters]';
  }

  // Prepend subject so the LLM always has full context even in isolated chunks
  const formattedContent = `Subject: ${msg.subject}\n\n${content}`;

  // Append a human-readable attachment list so agents immediately see what's attached.
  // Only appended when the message has real (non-inline) attachments.
  // NylasMessage.attachments is required — direct access is safe and avoids masking type errors.
  const attachments = msg.attachments;
  let finalContent = formattedContent;
  if (attachments.length > 0) {
    const summary = attachments
      .map((a) => `${a.filename} (${formatFileSize(a.size)})`)
      .join(', ');
    finalContent += `\n\n[Attachments: ${summary}]`;
  }

  // Collect participants in declaration order: from → to → cc
  // BCC is intentionally omitted — we don't expose hidden recipients downstream
  const participants: EmailParticipant[] = [
    ...msg.from.map((p) => ({ email: p.email, name: p.name, role: 'from' as const })),
    ...msg.to.map((p) => ({ email: p.email, name: p.name, role: 'to' as const })),
    ...msg.cc.map((p) => ({ email: p.email, name: p.name, role: 'cc' as const })),
  ];

  // Determine Curia's role in this email (To vs CC) when selfEmail is known.
  // Defaults to 'to' / empty primary recipients when selfEmail is not provided.
  const { curiaRole, primaryRecipientEmails } = selfEmail
    ? resolveCuriaRole(msg.to, msg.cc, selfEmail)
    : { curiaRole: 'to' as const, primaryRecipientEmails: [] };

  // Message-derived auto-generated classification (#1734). Uses headers,
  // calendar attachment method (consuming isCalendarInvite), and body emptiness
  // — not the sender contact's kind.
  const autoGenerated = toAutoGeneratedMetadata(
    classifyAutoGeneratedMail({
      subject: msg.subject,
      bodyText,
      snippet: msg.snippet ?? '',
      headers: msg.headers,
      attachments,
    }),
  );

  return {
    conversationId,
    channelId: 'email',
    senderId: fromEmail,
    content: finalContent,
    metadata: {
      subject: msg.subject,
      nylasMessageId: msg.id,
      nylasThreadId: msg.threadId,
      participants,
      // Nylas stores timestamps as Unix seconds; Date expects milliseconds
      receivedAt: new Date(msg.date * 1000),
      senderVerified: parseSenderVerified(msg.headers),
      curiaRole,
      primaryRecipientEmails,
      attachments,
      ...autoGenerated,
    },
  };
}
