// scripts/inspect-prompts.ts
// Prints, as JSON on stdout, the deployment-specific inputs agent system prompts are
// rendered from. curia-deploy's eval harness renders each agent's prompt locally from
// this snapshot with curia's own builders (curia-deploy#261), so it can score a local
// edit to an agent YAML or SKILL.md against this deployment's identity, roster,
// autonomy and contact details.
//
// Usage:
//   pnpm inspect-prompts
//   (expands to: tsx --env-file=.env scripts/inspect-prompts.ts)
//
// In production it is run inside the app container by curia-deploy's
// scripts/fetch-prompt-blocks.sh, which validates the output and adds the image's
// commit before writing tests/eval/prompt-blocks.json.
//
// The values come from the test-mode stack (createTestModeStack, llm: 'offline'),
// the same assembly path production boots through. So the specialist roster honours
// registry enablement, security.trust_thresholds are validated rather than defaulted
// (#1729), and every value is the one the coordinator's runtime config holds — the
// inputs buildBaseSystemPrompt() reads on a live turn. Nothing here re-derives them.
//
// Re-run when any of these change:
//   - Office identity (wizard / PUT /api/identity) or the autonomy score
//   - security.trust_thresholds in config/default.yaml
//   - Specialist agents (agents/*.yaml) or their registry enablement
//   - The principal's verified channel identities, or Curia's own email / Signal number
//
// Requires: DATABASE_URL pointing at a migrated Curia instance. No LLM key is needed —
// providers are offline and nothing is sent. SECRET_ENCRYPTION_KEY is optional; without
// it the Signal number is missing (a stderr warning says so).
//
// What it writes: only the idempotent bootstrap upserts every boot already performs
// (office identity seed, agent self-contact). It does not write registry rows, and it
// is safe to run beside a live instance.

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createTestModeStack, type TestModeStack } from '../src/startup/test-mode-stack.js';
import { createSilentLogger } from '../src/logger.js';

const REPO_ROOT = resolve(import.meta.dirname, '..');

/**
 * The snapshot. snake_case because it is a JSON file read by another repo. Every field
 * is a deployment-wide input; which agent receives which block is decided at render
 * time by resolveSystemPromptSources(), not here.
 */
export interface PromptInputsSnapshot {
  _note: string;
  /** The curia the inputs were taken from. The harness warns when its checkout differs. */
  curia: { version: string };
  timezone: string;
  office_identity_block: string;
  security_context_block: string;
  available_specialists: string;
  /** null when autonomy_config has no row (pre-migration) — production omits the block too. */
  autonomy: { score: number; band: string } | null;
  agent_contact_id: string | null;
  principal_contact_id: string | null;
  /** Verified + active only (readPrincipalIdentitySnapshot) — the fields the block renders. */
  principal_identities: Array<{ channel: string; channel_identifier: string; label: string | null }>;
  principal_primary_email: string | null;
  channel_accounts: { email: string | null; phone: string | null };
}

/** Read every input from the coordinator's runtime config, which is what production feeds the builder. */
export async function buildPromptInputsSnapshot(
  stack: Pick<TestModeStack, 'agent' | 'principalContactId'>,
  curiaVersion: string,
): Promise<PromptInputsSnapshot> {
  const rc = stack.agent('coordinator').runtimeConfig;

  // The coordinator always receives these. A missing one means assembly changed shape,
  // and a snapshot without it would silently render a coordinator with that block gone.
  if (!rc.officeIdentityService) throw new Error('coordinator runtime config has no officeIdentityService');
  if (!rc.securityContextBlock) throw new Error('coordinator runtime config has no securityContextBlock');
  if (rc.availableSpecialists === undefined) throw new Error('coordinator runtime config has no availableSpecialists');
  if (!rc.autonomyService) throw new Error('coordinator runtime config has no autonomyService');
  const timezone = rc.timezone?.trim();
  if (!timezone) throw new Error('coordinator runtime config has no timezone (TIMEZONE)');

  const autonomy = await rc.autonomyService.getConfig();

  return {
    _note: [
      'Generated by curia scripts/inspect-prompts.ts (via curia-deploy scripts/fetch-prompt-blocks.sh).',
      'Inputs, not rendered prompts: the eval harness renders each agent with curia\'s own builders.',
      'Holds instance-specific data (contact UUIDs, addresses, identity) — keep it out of git.',
    ].join(' '),
    curia: { version: curiaVersion },
    timezone,
    office_identity_block: rc.officeIdentityService.compileSystemPromptBlock(),
    security_context_block: rc.securityContextBlock,
    available_specialists: rc.availableSpecialists,
    autonomy: autonomy ? { score: autonomy.score, band: autonomy.band } : null,
    agent_contact_id: rc.agentContactId ?? null,
    principal_contact_id: stack.principalContactId ?? null,
    principal_identities: (rc.principalIdentities ?? []).map((id) => ({
      channel: id.channel,
      channel_identifier: id.channelIdentifier,
      label: id.label ?? null,
    })),
    principal_primary_email: rc.principalPrimaryEmail?.current ?? null,
    channel_accounts: {
      email: rc.channelAccounts?.email ?? null,
      phone: rc.channelAccounts?.phone ?? null,
    },
  };
}

function readCuriaVersion(): string {
  const pkg = JSON.parse(readFileSync(resolve(REPO_ROOT, 'package.json'), 'utf-8')) as { version?: unknown };
  if (typeof pkg.version !== 'string' || pkg.version.length === 0) {
    throw new Error('package.json has no version');
  }
  return pkg.version;
}

async function main(): Promise<void> {
  const stack = await createTestModeStack({ llm: 'offline', logger: createSilentLogger() });
  try {
    // The stack's logger is silent, so everything that makes these inputs differ from
    // what production holds is surfaced on stderr instead.
    for (const warning of stack.warnings) {
      process.stderr.write(`inspect-prompts: warning: ${warning}\n`);
    }
    const snapshot = await buildPromptInputsSnapshot(stack, readCuriaVersion());
    // process.stdout.write, not console.log — the caller parses this as JSON.
    process.stdout.write(JSON.stringify(snapshot, null, 2) + '\n');
  } finally {
    try {
      await stack.shutdown();
    } catch (err: unknown) {
      // Don't let teardown shadow a real error — the snapshot may already be written.
      process.stderr.write(`inspect-prompts: warning: shutdown failed: ${String(err)}\n`);
    }
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err: unknown) => {
    process.stderr.write(`inspect-prompts: fatal error\n${String(err)}\n`);
    process.exit(1);
  });
}
