import { describe, it, expect } from 'vitest';
import { Dispatcher } from '../../../src/dispatch/dispatcher.js';
import { EventBus } from '../../../src/bus/bus.js';
import { createLogger } from '../../../src/logger.js';
import {
  createInboundMessage,
  createAgentResponse,
  type AgentTaskEvent,
  type OutboundMessageEvent,
  type OutboundNoReplyEvent,
} from '../../../src/bus/events.js';
import type { ContactResolver } from '../../../src/contacts/contact-resolver.js';
import type { ContactKind } from '../../../src/contacts/types.js';

function makeResolver(opts: {
  kind?: ContactKind;
  systemRole?: 'principal' | 'agent' | 'system' | null;
  tier?: 'principal' | 'known' | 'unknown';
  contactConfidence?: number;
} = {}): ContactResolver {
  return {
    resolve: async () => ({
      resolved: true,
      contactId: opts.systemRole === 'principal' ? 'principal-1' : 'contact-person-1',
      displayName: opts.systemRole === 'principal' ? 'Principal' : 'Known Person',
      role: null,
      systemRole: opts.systemRole ?? null,
      tier: opts.tier ?? (opts.systemRole === 'principal' ? 'principal' : 'known'),
      kind: opts.kind ?? 'person',
      verified: true,
      kgNodeId: null,
      knowledgeSummary: '',
      authorization: null,
      contactConfidence: opts.contactConfidence ?? 0.8,
    }),
  } as unknown as ContactResolver;
}

function buildHarness(resolver: ContactResolver = makeResolver()) {
  const logger = createLogger('error');
  const bus = new EventBus(logger);
  const tasks: AgentTaskEvent[] = [];
  const outbound: OutboundMessageEvent[] = [];
  const noReply: OutboundNoReplyEvent[] = [];

  const dispatcher = new Dispatcher({
    bus,
    logger,
    contactResolver: resolver,
  });
  dispatcher.register();

  bus.subscribe('agent.task', 'agent', (e) => {
    tasks.push(e as AgentTaskEvent);
  });
  bus.subscribe('outbound.message', 'channel', (e) => {
    outbound.push(e as OutboundMessageEvent);
  });
  bus.subscribe('outbound.no_reply', 'system', (e) => {
    noReply.push(e as OutboundNoReplyEvent);
  });

  return { bus, dispatcher, tasks, outbound, noReply };
}

describe('Dispatcher auto-generated mail (#1734)', () => {
  it('dispatches RSVP reply from kind=person with silence preamble (does not skip agent.task)', async () => {
    const { bus, tasks, outbound, noReply } = buildHarness();

    await bus.publish(
      'channel',
      createInboundMessage({
        conversationId: 'email:thread-rsvp',
        channelId: 'email',
        senderId: 'colleague@example.com',
        content: 'Subject: Declined: Q3 Planning\n\n(empty email)\n\n[Attachments: invite.ics (120 B)]',
        metadata: {
          subject: 'Declined: Q3 Planning',
          isAutoGenerated: true,
          autoGeneratedSignals: ['calendar_reply'],
          attachments: [
            {
              id: 'att-1',
              filename: 'invite.ics',
              contentType: 'text/calendar; method=REPLY',
              size: 120,
              isCalendarInvite: true,
            },
          ],
          participants: [{ email: 'colleague@example.com', role: 'from' }],
        },
      }),
    );

    expect(tasks).toHaveLength(1);
    expect(tasks[0]!.payload.content).toContain('AUTO-GENERATED MAIL');
    expect(tasks[0]!.payload.content).toContain('calendar_reply');
    expect(tasks[0]!.payload.content).toContain('NO_REPLY');
    expect(outbound).toHaveLength(0);
    expect(noReply).toHaveLength(0);
  });

  it('still dispatches bounce notices so the agent can escalate', async () => {
    const { bus, tasks, outbound, noReply } = buildHarness();

    await bus.publish(
      'channel',
      createInboundMessage({
        conversationId: 'email:thread-bounce',
        channelId: 'email',
        senderId: 'mailer-daemon@example.com',
        content: 'Subject: Undeliverable: Report\n\nDelivery has failed.',
        metadata: {
          subject: 'Undeliverable: Report',
          isAutoGenerated: true,
          autoGeneratedSignals: ['auto_submitted'],
          participants: [{ email: 'mailer-daemon@example.com', role: 'from' }],
        },
      }),
    );

    expect(tasks).toHaveLength(1);
    expect(tasks[0]!.payload.content).toContain('AUTO-GENERATED MAIL');
    expect(tasks[0]!.payload.content).toContain('NO_REPLY');
    expect(noReply).toHaveLength(0);
    expect(outbound).toHaveLength(0);
  });

  it('suppresses the relay when an auto-gen turn still produces closing text', async () => {
    const { bus, dispatcher, tasks, outbound, noReply } = buildHarness();

    await bus.publish(
      'channel',
      createInboundMessage({
        conversationId: 'email:thread-bounce-2',
        channelId: 'email',
        senderId: 'mailer-daemon@example.com',
        content: 'Subject: Undeliverable: Report\n\nDelivery has failed.',
        metadata: {
          subject: 'Undeliverable: Report',
          isAutoGenerated: true,
          autoGeneratedSignals: ['auto_submitted'],
          participants: [{ email: 'mailer-daemon@example.com', role: 'from' }],
        },
      }),
    );
    expect(tasks).toHaveLength(1);

    await bus.publish(
      'system',
      createAgentResponse({
        agentId: 'coordinator',
        conversationId: 'email:thread-bounce-2',
        content: 'Thanks for letting me know about the delivery failure.',
        parentEventId: tasks[0]!.id,
      }),
    );

    expect(outbound).toHaveLength(0);
    expect(noReply).toHaveLength(1);
    expect(noReply[0]!.payload.reason).toBe('auto_generated');
    // Real agent.task id + real agent — not a fabricated inbound id / fake agent row
    expect(noReply[0]!.payload.routingTaskId).toBe(tasks[0]!.id);
    expect(noReply[0]!.payload.agentId).toBe('coordinator');
    expect(dispatcher).toBeDefined();
  });

  it('does not suppress principal-originated forwards that look auto-generated', async () => {
    const { bus, tasks, noReply } = buildHarness(
      makeResolver({ systemRole: 'principal', tier: 'principal' }),
    );

    await bus.publish(
      'channel',
      createInboundMessage({
        conversationId: 'email:thread-principal-fwd',
        channelId: 'email',
        senderId: 'ceo@example.com',
        content: 'Subject: Fwd: Out of Office: Jane Doe\n\nCan you try reaching them another way?',
        metadata: {
          subject: 'Fwd: Out of Office: Jane Doe',
          isAutoGenerated: true,
          autoGeneratedSignals: ['ooo_subject'],
          participants: [{ email: 'ceo@example.com', role: 'from' }],
        },
      }),
    );

    expect(tasks).toHaveLength(1);
    // Principal bypass: no silence preamble, normal dispatch
    expect(tasks[0]!.payload.content).not.toContain('AUTO-GENERATED MAIL');
    expect(noReply).toHaveLength(0);
  });

  it('dispatches a normal human email from the same contact to the coordinator', async () => {
    const { bus, tasks, noReply } = buildHarness();

    await bus.publish(
      'channel',
      createInboundMessage({
        conversationId: 'email:thread-human',
        channelId: 'email',
        senderId: 'colleague@example.com',
        content: 'Subject: Lunch tomorrow?\n\nWant to grab lunch?',
        metadata: {
          subject: 'Lunch tomorrow?',
          isAutoGenerated: false,
          autoGeneratedSignals: [],
          participants: [{ email: 'colleague@example.com', role: 'from' }],
        },
      }),
    );

    expect(tasks).toHaveLength(1);
    expect(tasks[0]!.payload.content).not.toContain('AUTO-GENERATED MAIL');
    expect(noReply).toHaveLength(0);
  });
});
