// Trigger detection for the coordinator's per-turn guidance (#1959): each key is present
// when its trigger is and absent otherwise.

import { describe, expect, it } from 'vitest';
import {
  inboundTurnGuidance,
  type InboundGuidanceFacts,
} from '../../../src/dispatch/turn-guidance-triggers.js';

function facts(overrides: Partial<InboundGuidanceFacts> = {}): InboundGuidanceFacts {
  return {
    liveTurn: true,
    injectedEntryMetadata: [],
    channelId: 'signal',
    curiaCc: false,
    autoGeneratedSuppress: false,
    ...overrides,
  };
}

const TASK_WAKE = { bind_reply: true, task_id: '3804c301-aaaa-4bbb-8ccc-dddddddddddd' };

describe('inboundTurnGuidance', () => {
  it('principal turn with no outbound block gets only the reply-shaped note', () => {
    expect(inboundTurnGuidance(facts())).toEqual(['principal-reply-shaped']);
  });

  it('principal turn with the block gets the block guidance instead of the note', () => {
    const keys = inboundTurnGuidance(facts({ injectedEntryMetadata: [null] }));
    expect(keys).toEqual(['outbound-context']);
  });

  it('non-principal turn gets the non-principal guidance, never the block guidance', () => {
    expect(inboundTurnGuidance(facts({ liveTurn: false }))).toEqual(['non-principal-reply-shaped']);
    // Entries never reach a non-principal turn, but even if a caller passed some, the
    // block guidance must not appear without the principal.
    const keys = inboundTurnGuidance(facts({ liveTurn: false, injectedEntryMetadata: [TASK_WAKE] }));
    expect(keys).toEqual(['non-principal-reply-shaped']);
  });

  describe('outbound-context sub-rules follow what the entries carry', () => {
    it.each([
      ['outbound-context-task-wake', TASK_WAKE],
      ['outbound-context-clarification', { resume_token: 'tok' }],
      ['outbound-context-debrief', { subject: 'Acme Q3 sync', eventId: 'evt-1' }],
    ] as const)('%s', (key, metadata) => {
      expect(inboundTurnGuidance(facts({ injectedEntryMetadata: [metadata] }))).toEqual([
        'outbound-context',
        key,
      ]);
      // An entry without that metadata does not trigger it.
      expect(inboundTurnGuidance(facts({ injectedEntryMetadata: [{ meeting: 'x' }] }))).not.toContain(key);
    });

    it('needs a task_id for the task-wake rule, and non-empty token and subject', () => {
      const keys = inboundTurnGuidance(facts({
        injectedEntryMetadata: [{ bind_reply: true }, { resume_token: '' }, { subject: '  ' }],
      }));
      expect(keys).toEqual(['outbound-context']);
    });

    it('collects every sub-rule present across entries', () => {
      const keys = inboundTurnGuidance(facts({
        injectedEntryMetadata: [TASK_WAKE, { resume_token: 'tok' }, { subject: 'Standup' }],
      }));
      expect(keys).toEqual([
        'outbound-context',
        'outbound-context-task-wake',
        'outbound-context-clarification',
        'outbound-context-debrief',
      ]);
    });
  });

  describe('email', () => {
    it('a direct email gets the direct-reply rule and the etiquette', () => {
      const keys = inboundTurnGuidance(facts({ channelId: 'email', liveTurn: false }));
      expect(keys).toEqual(['non-principal-reply-shaped', 'email-direct-reply', 'email-etiquette']);
    });

    it('a CC from the principal gets the CC judgment and CC reply mechanics, not the direct rule', () => {
      const keys = inboundTurnGuidance(facts({ channelId: 'email', curiaCc: true }));
      expect(keys).toEqual(['principal-reply-shaped', 'email-cc-principal', 'email-cc-reply', 'email-etiquette']);
    });

    it('a CC from someone else gets the CC reply mechanics without the principal judgment', () => {
      const keys = inboundTurnGuidance(facts({ channelId: 'email', curiaCc: true, liveTurn: false }));
      expect(keys).toContain('email-cc-reply');
      expect(keys).not.toContain('email-cc-principal');
      expect(keys).not.toContain('email-direct-reply');
    });

    it('a non-email turn gets no email guidance', () => {
      for (const channelId of ['signal', 'sms', 'slack', 'cli', 'http']) {
        expect(inboundTurnGuidance(facts({ channelId })).some((k) => k.startsWith('email-'))).toBe(false);
      }
    });
  });

  it('suppressed auto-generated mail gets nothing: its preamble already says NO_REPLY', () => {
    expect(inboundTurnGuidance(facts({ channelId: 'email', liveTurn: false, autoGeneratedSuppress: true }))).toEqual([]);
  });
});
